// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	feattd_firm "zero-zone/app/core/cmd/api/internal/handler/feat/td_firm"
	"zero-zone/app/core/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: feattd_firm.TdFirmCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: feattd_firm.TdFirmDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deletes",
				Handler: feattd_firm.TdFirmDeletesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: feattd_firm.TdFirmDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: feattd_firm.TdFirmListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/page",
				Handler: feattd_firm.TdFirmPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: feattd_firm.TdFirmUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/admin/feat/tdFirm"),
	)
}
