// Code generated by goctl. DO NOT EDIT.
package types



type PageReq struct {
	Page  int64 `form:"page"  validate:"number,gte=1"  label:"页数"`
	Limit int64 `form:"limit" validate:"number,gte=1"  label:"条数"`
}

type Pagination struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
	Total int64 `json:"total"`
}

type TdFirm struct {
	FirmId    int64  `json:"firmId"`
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}

type TdFirmCreateReq struct {
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}

type TdFirmCreateResp struct {
	FirmId    int64  `json:"firmId"`
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}

type TdFirmDeleteReq struct {
	FirmId int64 `json:"firmId"`
}

type TdFirmDeleteResp struct {
	FirmId int64 `json:"firmId"`
}

type TdFirmDeletesReq struct {
	FirmId []int64 `json:"firmId"`
}

type TdFirmDeletesResp struct {
	FirmId int64 `json:"[]firmId"`
}

type TdFirmDetailReq struct {
	FirmId int64 `form:"firmId"`
}

type TdFirmDetailResp struct {
	FirmId    int64  `json:"firmId"`
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}

type TdFirmListReq struct {
	FirmName  *string `form:"firmName,optional"`
	FirmAlias *string `form:"firmAlias,optional"`
	FirmCode  *string `form:"firmCode,optional"`
	FirmDesc  *string `form:"firmDesc,optional"`
}

type TdFirmListResp struct {
	List  []TdFirm `json:"list"`
	Total int64     `json:"total"`
}

type TdFirmPageReq struct {
	PageReq
	FirmName  *string `form:"firmName,optional"`
	FirmAlias *string `form:"firmAlias,optional"`
	FirmCode  *string `form:"firmCode,optional"`
	FirmDesc  *string `form:"firmDesc,optional"`
}

type TdFirmPageResp struct {
	List       []TdFirm  `json:"list"`
	Pagination Pagination `json:"pagination"`
}

type TdFirmUpdateReq struct {
	FirmId    int64  `json:"firmId"`
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}

type TdFirmUpdateResp struct {
	FirmId    int64  `json:"firmId"`
	FirmName  string `json:"firmName"`
	FirmAlias string `json:"firmAlias"`
	FirmCode  string `json:"firmCode"`
	FirmDesc  string `json:"firmDesc"`
}
